guest_list = ["Albert Einstein" , "Nikola Tesla" , "Werner Heisenberg"]
welcome_message = (f"I would like to formally invite you to a dinner. This table will be filled by the minds that shaped our world, will you attend for a feast and talks that will strain the very cosmos itself?")
Einstein_message = (f"{guest_list[0].title()} , {welcome_message}") 
Tesla_message = (f"{guest_list[1].title()} , {welcome_message}")
Heisenberg_message = (f"{guest_list[2].title()} , {welcome_message}")
print (Einstein_message)
print (Tesla_message)
print (Heisenberg_message)
print (f"{guest_list[0]} , {guest_list[1]} , {guest_list[2]} , I have found a bigger table, and would like to add minds from the modern era to our feast.")
guest_list.insert (0 , 'Neil deGrasse Tyson')
guest_list.insert (2 , 'Michio Kaku')
guest_list.append ('Brian Cox')
guest_list.sort()
updated_welcome_message = ('I bid hello to the minds that shaped the foundations of physics and beyond. Also a welcome to the minds that took that knowledge further. Please join me for a feast and a discussion for the history books.')
print (f"{guest_list [0]} , {updated_welcome_message}")
print (f"{guest_list [1]} , {updated_welcome_message}")
print (f"{guest_list [2]} , {updated_welcome_message}")
print (f"{guest_list [3]} , {updated_welcome_message}")
print (f"{guest_list [4]} , {updated_welcome_message}")
print (f"{guest_list [5]} , {updated_welcome_message}")

